<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity;


use Gecche\Cupparis\App\Enums\CupparisTipiCampi;
use App\Models\CupparisEntityField;
use Gecche\Cupparis\App\Foorm\Base\FoormInsert as BaseFoormInsert;
use Gecche\DBHelper\Facades\DBHelper;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class FoormEdit extends BaseFoormInsert
{

    use CupparisEntityTrait;

    protected $files;

    protected $fieldsText;


    protected function init()
    {
        $this->files = new Filesystem();
        $this->modelsList = $this->getModelsList();
        parent::init(); // TODO: Change the autogenerated stub
    }



}
