<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity;


use Gecche\Cupparis\App\Enums\CupparisTipiCampi;
use App\Models\CupparisEntityField;
use Gecche\Cupparis\App\Foorm\Base\FoormInsert as BaseFoormInsert;
use Gecche\DBHelper\Facades\DBHelper;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class FoormInsert extends BaseFoormInsert
{
    use CupparisEntityTrait;
    use CupparisEntityGuessTrait;

    protected $fieldsText;


    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initOps();
        $this->modelsList = $this->getModelsList();
    }


    protected function setFieldsToModel($model, $configFields, $input)
    {
        $originalFormType = Arr::get($this->config, 'original_form_type');
        switch ($originalFormType) {
            case 'insert_express':
                $this->fieldsText = explode(",", Arr::pull($input, 'fields_text'));
                break;
            default:
                break;
        }

        parent::setFieldsToModel($model, $configFields, $input);
    }

    protected function saveModel($input)
    {

        $originalFormType = Arr::get($this->config, 'original_form_type');
        $saved = parent::saveModel($input);
        switch ($originalFormType) {
            case 'insert_express':
                $nonIdFields = 0;
                foreach ($this->fieldsText as $fieldName) {
                    $isId = Str::endsWith($fieldName, '_id');
                    if (!$isId) {
                        $nonIdFields++;
                    }
                    $fieldName = trim($fieldName);
                    list($tipoCampo, $informazioni) = $this->guessCampo($fieldName, $isId);
                    $defaultValue = in_array($tipoCampo, [CupparisTipiCampi::BOOLEAN->value, CupparisTipiCampi::INTEGER->value])
                        ? 0 : null;
                    $indexValue = in_array($fieldName, ['codice', 'code']) ? 'UNIQUE' :
                        ($tipoCampo == CupparisTipiCampi::ID_INTEGER->value ? 'INDEX' : null);
                    $relazioneModello = $this->guessRelationModel($fieldName);
                    $widgetSearch = $this->guessWidgetSearch($fieldName, $tipoCampo, $relazioneModello);
                    $widgetList = $this->guessWidgetList($fieldName, $tipoCampo, $relazioneModello);
                    $widgetEdit = $this->guessWidgetEdit($fieldName, $tipoCampo, $relazioneModello);
                    $cupparisEntityField = new CupparisEntityField([
                        'entity_id' => $this->model->getKey(),
                        'nome' => $fieldName,
                        'tipo' => $tipoCampo,
                        'nullable' => (!$isId && $nonIdFields < 1) ? 0 : 1,
                        'informazioni' => $informazioni,
                        'default' => $defaultValue,
                        'index' => $indexValue,
                        'relazione_tabella' => $relazioneModello,
                        'relazione_campo' => $isId ? 'id' : null,
                        'on_delete' => $isId ? 'RESTRICT' : null,
                        'on_update' => $isId ? 'CASCADE' : null,
                        'model_conf_search' => $widgetSearch,
                        'model_conf_list' => $widgetList,
                        'model_conf_edit' => $widgetEdit,
                    ]);
                    $cupparisEntityField->save();
                }
                $this->model->load(['fields']);
                break;
            default:
                break;
        }


        return $saved;
    }


}
