<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity;


use Gecche\Cupparis\App\Foorm\Base\FoormInsert as BaseFoormInsert;

class FoormEdit extends BaseFoormInsert
{

    use CupparisEntityTrait;


    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initOps();
        $this->modelsList = $this->getModelsList();
    }



}
