<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity;

use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Log;

class FoormList extends \Gecche\Cupparis\App\Foorm\Base\FoormList
{
    public function finalizeData()
    {
        parent::finalizeData(); // TODO: Change the autogenerated stub
        foreach (array_keys(Arr::get($this->formData,'data',[])) as $key) {
            $this->formData['data'][$key]['cosa_migrare'] = ['tutto'];
        }
    }


}
