<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity;


use Gecche\Cupparis\App\Enums\CupparisTipiCampi;
use App\Models\CupparisEntityField;
use Gecche\Cupparis\App\Foorm\Base\FoormInsert as BaseFoormInsert;
use Gecche\DBHelper\Facades\DBHelper;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class FoormInsert extends BaseFoormInsert
{
    use CupparisEntityTrait;
    use CupparisEntityGuessTrait;

    protected $fieldsText;


    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initOps();
        $this->modelsList = $this->getModelsList();
    }


    protected function setFieldsToModel($model, $configFields, $input)
    {
        $originalFormType = Arr::get($this->config, 'original_form_type');
        switch ($originalFormType) {
            case 'insert_express':
                $this->fieldsText = explode(",", Arr::pull($input, 'fields_text'));
                break;
            default:
                break;
        }

        parent::setFieldsToModel($model, $configFields, $input);
    }

    protected function saveModel($input)
    {

        $originalFormType = Arr::get($this->config, 'original_form_type');
        $saved = parent::saveModel($input);
        switch ($originalFormType) {
            case 'insert_express':
                $this->guessCupparisEntityFields($this->model,$this->fieldsText);
                $this->model->load(['fields']);
                break;
            default:
                break;
        }


        return $saved;
    }


}
