<?php

namespace Gecche\Cupparis\App\Foorm\Base;


use Gecche\Cupparis\App\Breeze\Breeze;
use Gecche\Cupparis\App\Foorm\Base\FoormList;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class FoormDatafileList extends FoormList
{

    protected $datafileProviderClass = null;
    protected $datafileProvider = null;

    protected $datafileId = null;

    protected function generateListBuilder()
    {
        parent::generateListBuilder(); // TODO: Change the autogenerated stub

        $datafileIdContraint = [
            'field' => 'datafile_id',
            'op' => '=',
            'value' => $this->datafileId,
        ];

        $this->applyConstraint($datafileIdContraint);
    }


    protected function beforeDataPreparation()
    {
        $provider = Arr::get($this->config, 'datafile_provider');

        if (!$provider) {
            throw new \Exception("Datafile provider missing");
        }

        $this->datafileProviderClass = config('cupparis-datafile-json.providers.'.$provider);

        if (!$this->datafileProviderClass) {
            throw new \Exception("Datafile provider not found in cupparis-datafile-json config");
        }

        $this->datafileProvider = new $this->datafileProviderClass();

        $headers = $this->datafileProvider->getHeaders();

        $fields = Arr::get($this->config, 'fields', []);

        foreach ($headers as $header) {

            $fields[$header] = Arr::get($fields,$header,[]);
        }

        $fields['row'] = [];

        $this->config['fields'] = $fields;

        $this->datafileId = Arr::get($this->params, 'datafile_id');

        if (!$this->datafileId) {
            throw new \Exception("Datafile id missing");
        }

    }

    protected function finalizeDataStandard()
    {

        $arrayData = $this->formBuilder->toArray();

        $arrayDataData = Arr::get($arrayData,'data',[]);

        foreach ($arrayDataData as $key => $arrayDatum) {
            $rowData = Arr::pull($arrayDatum,'row_data',[]);
            $rowDataValues = Arr::get($rowData,'values',[]);
            $rowDataErrors = Arr::get($rowData,'errors',[]);
            $arrayDatum = array_merge($arrayDatum,$rowDataValues);
            $arrayDataData[$key] = $arrayDatum;
            $arrayData['errors'][$key] = $rowDataErrors;
        }

        $arrayData['data'] = $arrayDataData;

        $paginationSteps = Arr::get(Arr::get($this->config, 'pagination', []),'pagination_steps',[]);

        $arrayData['pagination_steps'] = array_combine($paginationSteps,$paginationSteps);
        return $arrayData;
    }

}
