<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity\Actions;

use App\Models\CupparisEntity;
use Gecche\Cupparis\App\Enums\CupparisTipiCampi;
use App\Models\CupparisEntityField;
use Gecche\Cupparis\App\Foorm\CupparisEntity\CupparisEntityGuessTrait;
use Gecche\Foorm\FoormAction;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Gecche\DBHelper\Facades\DBHelper;


class Import extends FoormAction
{
    use MigrateRollbackTrait;
    use CupparisEntityGuessTrait;


    protected $entitiesSkipped = [];
    protected $entitiesInstantianted = [];
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initOps();
        $this->modelsList = $this->getModelsList();
    }


    public function performAction()
    {
        foreach ($this->getModelsList() as $modelName) {
            $entity = CupparisEntity::where('model_class',$modelName)
                ->first();
            if ($entity) {
                $this->entitiesSkipped[$modelName] = $modelName;
                continue;
            }

            $tableName = $entity->getTable();
            $columns = DBHelper::listColumnsDefault($tableName);

            Log::info($columns);
        }
//
//        $this->saveMigration();
//        $this->saveModel();
//        $this->savePolicy();
//        $this->saveFoorm();
//        $this->saveModelConf();
//        $this->manageConfigs($this->getConfigsData(),'i');
//        $this->saveLangs();
        $this->actionResult = [

        ];

        return $this->actionResult;        // TODO: Implement performAction() method.
    }

    public function validateAction()
    {
        return true;
        // TODO: Implement validateAction() method.
    }


}
