<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity\Actions;

use App\Models\CupparisEntity;
use Gecche\Cupparis\App\Enums\CupparisTipiCampi;
use App\Models\CupparisEntityField;
use Gecche\Cupparis\App\Foorm\CupparisEntity\CupparisEntityGuessTrait;
use Gecche\Foorm\FoormAction;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Gecche\DBHelper\Facades\DBHelper;


class Import extends FoormAction
{
    use MigrateRollbackTrait;
    use CupparisEntityGuessTrait;

    protected $entitiesSkipped = [];
    protected $entitiesInstantianted = [];

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initOps();
        $this->modelsList = $this->getModelsList();
    }


    public function performAction()
    {
        $modelsToExclude = [
            'CupparisEntity',
            'CupparisEntityField',
            'Foto',
            'Attachment',
            'Role',
            'Permission',
            'User',
            'DatafileJson',
            'DatafileJsonRow',
        ];
        foreach ($this->getModelsList() as $modelName) {
            if (in_array($modelName, $modelsToExclude)) {
                continue;
            }
            $entity = CupparisEntity::where('model_class', $modelName)
                ->first();
            if ($entity) {
                $this->entitiesSkipped[$modelName] = $modelName;
                continue;
            }

            $entity = new CupparisEntity();



            $modelClass = $this->modelsNamespaces . $modelName;
            $model = new $modelClass;
            $relationData = $modelClass::getRelationsData();

            $entity->nome = $model->getTable();
            $entity->model_class = $modelName;
            $entity->has_foto = array_key_exists('fotos',$relationData);
            $entity->has_attachments = array_key_exists('attachments',$relationData);


            $tableName = $model->getTable();
            $dbHelpers = DBHelper::helper($model->getconnection()->getName());

            $columns = $dbHelpers->listColumnsDefault($tableName);
            $timestamps = Arr::get($columns,'created_at',[]);
            $ownerships = Arr::get($columns,'created_by',[]);

            if (count($timestamps) <= 0) {
                $entity->timestamps = 0;
            } elseif (Arr::get($timestamps,'column_default') === 'NULL') {
                $entity->timestamps = 'nullable';
            } else {
                $entity->timestamps = 1;
            }

            if (count($ownerships) <= 0) {
                $entity->ownerships = 0;
            } elseif (Arr::get($ownerships,'column_default') === 'NULL') {
                $entity->ownerships = 'nullable';
            } else {
                $entity->ownerships = 1;
            }

            $entity->columns_list =
                is_array($model->columnsForSelectList) && count($model->columnsForSelectList) > 0
                    ? $model->columnsForSelectList : ['id'];

            if (is_array($model->defaultOrderColumns) && count($model->defaultOrderColumns) > 0) {
                $entity->columns_order = ['id_asc'];
            }  else {
                $entity->columns_order = [];
                foreach ($model->defaultOrderColumns as $orderColumn => $orderDir) {
                    $entity->columns_order[] = $orderColumn . '_' . strtolower($orderDir);
                }
            }

            $langEntry = Lang::get('model.'.Str::snake($modelName));
            $langEntryArray = explode('|',$langEntry);
            $entity->lang_singolare = Arr::get($langEntryArray,0,Str::snake($modelName));
            $entity->lang_plurale = Arr::get($langEntryArray,1,Str::snake($tableName));

            $entity->save();
            $columnsToExclude = [
                'id',
                'created_at',
                'updated_at',
                'created_by',
                'updated_by'
            ];
            $fieldsText = array_keys(Arr::except($columns, $columnsToExclude));



            $this->guessCupparisEntityFields($entity,$fieldsText);


        }
//
//        $this->saveMigration();
//        $this->saveModel();
//        $this->savePolicy();
//        $this->saveFoorm();
//        $this->saveModelConf();
//        $this->manageConfigs($this->getConfigsData(),'i');
//        $this->saveLangs();
        $this->actionResult = [

        ];

        return $this->actionResult;        // TODO: Implement performAction() method.
    }

    public function validateAction()
    {
        return true;
        // TODO: Implement validateAction() method.
    }


}
