<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity\Actions;

use Gecche\Cupparis\App\Enums\CupparisTipiCampi;
use App\Models\CupparisEntityField;
use Carbon\Carbon;
use Gecche\Foorm\FoormAction;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class Migrate extends FoormAction
{
    use MigrateRollbackTrait;


    protected function init()
    {
        $this->initOps();


        parent::init(); // TODO: Change the autogenerated stub


    }


    public function performAction()
    {
        $this->saveMigration();
        $this->saveModel();
        $this->savePolicy();
        $this->saveFoorm();
        $this->saveModelConf();
        $this->manageConfigs($this->getConfigsData(),'i');
        $this->saveLangs();
        $this->actionResult = [

        ];

        return $this->actionResult;        // TODO: Implement performAction() method.
    }

    public function validateAction()
    {
        return true;
        // TODO: Implement validateAction() method.
    }


    public function saveMigration()
    {

        if (!$this->checkDaFare('migration')) {
            return;
        };

        $stub = $this->files->get($this->getStub());

        $migrationTable = $this->model->nome;

        $stub = str_replace(
            '{{$migrationTable}}', $migrationTable, $stub
        );

        $fields = $this->model->fields;

        $migrationCampi = $this->getIndent() . '$table->id();' . "\n";

        foreach ($fields as $field) {
            $migrationCampi .= $this->getIndent();


            $migrationCampi .= $this->getCampoString($field);


        }
        $stub = str_replace(
            '{{$migrationCampi}}', $migrationCampi, $stub
        );

        $timestampsStringValue = $this->getTimestampsOwnerships('timestamps', $this->model->timestamps);
        $stub = str_replace(
            '{{$timestamps}}', $timestampsStringValue, $stub
        );
        $ownershipsStringValue = $this->getTimestampsOwnerships('ownerships', $this->model->ownerships);
        $stub = str_replace(
            '{{$ownerships}}', $ownershipsStringValue, $stub
        );

        $filename = date('Y_m_d_His') . '_create_' . $migrationTable . '_table.php';

        $this->files->put(base_path($this->migrationPath . $filename), $stub);


    }

    protected function getTimestampsOwnerships($tipo, $value)
    {
        switch ($value) {
            case 'nullable':
                return $this->getIndent() . '$table->nullable' . ucfirst($tipo) . '();';
            case 1:
                return $this->getIndent() . '$table->' . $tipo . '();';
            default:
                return '';
        }
    }

    protected function getCampoString($field)
    {

        $fieldName = $field->nome;

        $fieldString = '$table->';
        $type = $field->tipo;
        $info = $field->informazioni;
        $info = array_map('trim', explode(',', $info));
        $infoString = '';

        switch ($type) {

            case 'enum':
                foreach ($info as $option) {
                    $infoString .= "'" . $option . "',";
                }
                if ($infoString) {
                    $infoString = trim($infoString, ',');
                    $infoString = ',[' . $infoString . ']';
                } else {
                    $infoString = ',[]';
                }
                break;
            default:
                $infoString = count($info) > 0 ? ',' . implode(',', $info) : '';
                break;
        }

        $infoString = rtrim($infoString, ', ');

        switch ($type) {
            case 'integer':
                $fieldString .= 'unsignedInteger(\'' . $fieldName . '\'' . $infoString . ')';
                break;
            case 'id_integer':
                $fieldString .= 'unsignedBigInteger(\'' . $fieldName . '\'' . $infoString . ')';
                break;
            case 'text':
                $fieldString .= 'longText(\'' . $fieldName . '\'' . $infoString . ')';
                break;
            default:
                $fieldString .= $type . '(\'' . $fieldName . '\'' . $infoString . ')';
                break;
        }

        if ($field->nullable) {
            $fieldString .= '->nullable()';
        }

        if ($field->default) {
            switch ($type) {
                case 'integer':
                case 'id_integer':
                case 'decimal':
                case 'boolean':
                case 'float':
                    $fieldString .= '->default(' . $field->default . ')';
                    break;

                default:
                    $fieldString .= '->default(\'' . $field->default . '\')';
                    break;
            }

        }


        $relationString = '';
        if ($field->relazione_tabella) {
            $modelClass = "App\\Models\\" . $field->relazione_tabella;
            $model = new $modelClass();

            //VINCOLO A CREARE UN INDICE NON UNICO SUL CAMPO PER LA RELAZIONE
            $relationString = '$table->foreign(\'' . $fieldName . '\')';
            $relationString .= '->references(\'' . ($field->relazione_campo ?: 'id') . '\')';
            $relationString .= '->on(\'' . $model->getTable() . '\')';
            $relationString .= '->onDelete(\'' . $field->on_delete . '\')';
            $relationString .= '->onUpdate(\'' . $field->on_update . '\')';


        }

        switch ($field->index) {
            case 'INDEX':
                $fieldString .= '->index()';
                break;
            case 'UNIQUE':
                $fieldString .= '->unique()';
                break;
            default:
                break;
        }

        $fieldString = $fieldString . ';';

        if ($relationString) {
            $fieldString = $fieldString . "\n" . $this->getIndent() . $relationString . ';';
        }
        return $fieldString;
    }


    public function saveModel()
    {
        if (!$this->checkDaFare('modello')) {
            return;
        };


        $filename = base_path(Arr::get($this->msConfig, 'modelsPath') . $this->model->model_class . '.php');

        $stub = $this->files->get($this->getStub('model'));
        $variables = [];

        $columns_for_select_list = $this->model->columns_list;
        $columns_for_default_order = [];

        $informazioni = $this->model->informazioni;

        foreach ($this->model->columns_order as $columnOrder) {
            $columns_for_default_order[Str::beforeLast($columnOrder, '_')] =
                strtoupper(Str::afterLast($columnOrder, '_'));
        }

//        $this->setApici($variables['columnsForSelectList']);

        $variables['columnsForSelectList'] = varexport($columns_for_select_list);
        $variables['defaultOrderColumns'] = varexport($columns_for_default_order);
        $variables['columnsSearchAutoComplete'] = varexport($columns_for_select_list);

        $variables['relationsData'] = "";
        foreach ($this->model->fields as $field) {
            if (!$field->relazione_tabella) {
                continue;
            }
            $nome = $field->nome;
            if (Str::endsWith($nome, '_id')) {
                $nome = Str::beforeLast($nome, '_id');
            } else {
                $nome = Str::snake($field->relazione_tabella);
            }

            $variables['relationsData'] .= $this->getIndent() . "'$nome' => [self::BELONGS_TO, 'related' => " . $field->relazione_tabella . "::class, 'foreignKey' => '$field->nome'],\n";


        }

        $variables['relationFoto'] = $this->model->has_foto ? "'fotos' => [self::MORPH_MANY, 'related' => Foto::class, 'name' => 'mediable']," : '';
        $variables['relationAttachments'] = $this->model->has_attachments ? "'attachments' => [self::MORPH_MANY, 'related' => Attachment::class, 'name' => 'mediable']," : '';


        $variables['timestamps'] = !$this->model->timestamps ? 'false' : 'true';
        $variables['ownerships'] = !$this->model->ownerships ? 'false' : 'true';

        $stub = str_replace(
            '{{$migrationTable}}', $this->model->nome, $stub
        );

        $stub = str_replace(
            '{{$modelClass}}', $this->model->model_class, $stub
        );

        foreach ($variables as $variableKey => $variableValue) {
            $stub = str_replace(
                '{{$' . $variableKey . '}}', $variableValue, $stub
            );
        }


        $this->files->put($filename, $stub);


    }


    protected function saveLangs() {

        if (!$this->checkDaFare('lang')) {
            return;
        };

        /*
         * SALVO I FIELDS NEL LANG
         */

        $configStubName = $this->getStub('config');
        $configStub = $this->files->get($configStubName);

        foreach ($this->langs['model'] as $modelLangFile) {
            $this->saveLangFile($modelLangFile, $configStub, 'model');
        }

        foreach ($this->langs['fields'] as $fieldsLangFile) {
            $this->saveLangFile($fieldsLangFile, $configStub, 'fields');
        }
    }

    protected function saveLangFile($resourceFile, $configStub, $type = 'model')
    {
        $filename = resource_path($resourceFile);

        if (!$this->files->exists($filename)) {
            $parentDir = $this->files->dirname($filename);
            if (!$this->files->isDirectory($parentDir)) {
                $this->files->makeDirectory($parentDir, 0755, true);
            }

            $this->files->put($filename, '<?php return []; ?>');
        }


        $langs = include $filename;

        switch ($type) {
            case 'model':

                $singolare = $this->model->lang_singolare;
                $plurale = $this->model->lang_plurale;
                $langs[$this->snakeModel] = "$singolare|$plurale";

                break;
            case 'fields':
                foreach ($this->model->fields as $field) {
                    $nome = $field->nome;
                    if (!array_key_exists($nome, $langs)) {
                        $langs[$nome] = Lang::getM($nome);
                    }
                }
                break;
            default:
                break;
        }


        $modelConfigStub = str_replace(
            '{{$configArray}}', varexport($langs), $configStub
        );

        $this->files->put($filename, $modelConfigStub);

    }


    public function savePolicy()
    {

        if (!$this->checkDaFare('policy')) {
            return;
        };

        $modelName = $this->model->model_class;

        $filename = base_path(Arr::get($this->msConfig, 'policiesPath') . $modelName . 'Policy.php');

        $stub = $this->files->get($this->getStub('policy'));
        $variables = [];

        $modelNameForPermission = $this->snakeModel;

        $permissions = [
            'viewPermission' => 'view ' . $modelNameForPermission,
            'viewAllPermission' => 'view all ' . $modelNameForPermission,
            'updatePermission' => 'edit ' . $modelNameForPermission,
            'deletePermission' => 'delete ' . $modelNameForPermission,
            'createPermission' => 'create ' . $modelNameForPermission,
            'listingPermission' => 'listing ' . $modelNameForPermission,
        ];

        $stub = str_replace(
            '{{$modelClass}}', $modelName, $stub
        );

        foreach ($permissions as $permissionKey => $permissionValue) {
            $stub = str_replace(
                '{{$' . $permissionKey . '}}', $permissionValue, $stub
            );
        }

        foreach ($variables as $variableKey => $variableValue) {
            $stub = str_replace(
                '{{$' . $variableKey . '}}', $variableValue, $stub
            );
        }


        $this->files->put($filename, $stub);

    }


    public function saveFoorm()
    {
        if (!$this->checkDaFare('foorm')) {
            return;
        };


        $filename = base_path("config/foorms/" . $this->snakeModel . '.php');

        $stub = $this->files->get($this->getStub('foorm'));


        $campi = $this->model->fields;

        $campi->add(new CupparisEntityField(['nome' => 'id', 'tipo' => 'integer']));

        $relazioni = [];

        $campiFinali = [];
        foreach ($campi as $field) {
            $campiFinali[$field->nome] = [];
            if ($field->relazione_tabella) {
                $nome = $field->nome;
                if (Str::endsWith($nome, '_id')) {
                    $relazioni[$nome] = Str::beforeLast($nome, '_id');
                } else {
                    $relazioni[$nome] = Str::snake($field->relazione_tabella);
                }
            }
        }

        $campiFinaliSearch = [];
        $campiFinaliEdit = [];
        foreach ($campi as $campo) {


            switch ($campo->tipo) {
                case 'string':
                    $campoSearchArray = [
                        'operator' => 'like',
                    ];
                    $campoEditArray = [];
                    break;
                case 'enum':
                    $campoSearchArray = [
                        'operator' => '=',
                        'options' => 'dboptions',
                    ];
                    $campoEditArray = [
                        'options' => 'dboptions',
                    ];
                    break;
                case 'boolean':
                    $campoSearchArray = [
                        'operator' => '=',
                        'options' => 'boolean',
                    ];
                    $campoEditArray = [
                        'options' => 'boolean',
                    ];
                    break;
                case 'id_integer':
                    if ($campo->relazione_tabella) {
                        $relation = Arr::get($relazioni, $campo->nome);
                    }
                    if ($relation) {
                        $campoSearchArray = [
                            'operator' => '=',
                            'options' => 'relation:' . $relation,
                        ];
                        $campoEditArray = [
                            'options' => 'relation:' . $relation,
                        ];
                    } else {
                        $campoSearchArray = [];
                        $campoEditArray = [];
                    }
                    break;

                default:
                    $campoSearchArray = [];
                    $campoEditArray = [];
                    break;
            }

            $campiFinaliSearch[$campo->nome] = $campoSearchArray;
            $campiFinaliEdit[$campo->nome] = $campoEditArray;
        }


        $relazioniFinaliList = [];
        $relazioniFinaliEdit = [];
        foreach ($relazioni as $relazione) {
            $relazioniFinaliList[$relazione] = [
                'fields' => [

                ],
            ];
        }

        if ($this->model->has_foto) {
            $relazioniFinaliList['fotos'] = [
                'fields' => [
                    'id' => [],
                    'nome' => [],
                    'descrizione' => [],
                    'resource' => []
                ]
            ];
            $relazioniFinaliEdit['fotos'] = [
                'fields' => [
                    'id' => [],
                    'nome' => [],
                    'descrizione' => [],
                    'resource' => [],
                ],
                //'saveType' => 'add',
                'orderKey' => 'ordine',

                'beforeNewCallbackMethods' => ['setFieldsFromResource'],
                'beforeUpdateCallbackMethods' => ['setFieldsFromResource'],
                'afterNewCallbackMethods' => ['filesOps'],
                'afterUpdateCallbackMethods' => ['filesOps'],
            ];
        }
        if ($this->model->has_attachments) {
            $relazioniFinaliList['attachments'] = [
                'fields' => [
                    'id' => [],
                    'nome' => [],
                    'descrizione' => [],
                    'resource' => []
                ]
            ];
            $relazioniFinaliEdit['attachments'] = [
                'fields' => [
                    'id' => [],
                    'nome' => [],
                    'descrizione' => [],
                    'resource' => [],
                ],
                //'saveType' => 'add',
                'orderKey' => 'ordine',

                'beforeNewCallbackMethods' => ['setFieldsFromResource'],
                'beforeUpdateCallbackMethods' => ['setFieldsFromResource'],
                'afterNewCallbackMethods' => ['filesOps'],
                'afterUpdateCallbackMethods' => ['filesOps'],
            ];
        }

        $variables = [];

        $stub = str_replace(
            '{{$fields}}', varexport($campiFinali), $stub
        );
        $stub = str_replace(
            '{{$fieldsSearch}}', varexport($campiFinaliSearch), $stub
        );
        $stub = str_replace(
            '{{$fieldsEdit}}', varexport($campiFinaliEdit), $stub
        );
        $stub = str_replace(
            '{{$relations}}', varexport($relazioniFinaliList), $stub
        );
        $stub = str_replace(
            '{{$relationsEdit}}', varexport($relazioniFinaliEdit), $stub
        );

        foreach ($variables as $variableKey => $variableValue) {
            $stub = str_replace(
                '{{$' . $variableKey . '}}', $variableValue, $stub
            );
        }


        $this->files->put($filename, $stub);

    }

    protected function buildModelConfValues(&$fieldsArray, CupparisEntityField $entityField, $type)
    {
        if (!$entityField->$type) {
            return;
        }
        $fieldArray = [
            'nome' => $entityField->nome,
            'type' => $entityField->$type,
            'order' => in_array($entityField->tipo, [CupparisTipiCampi::STRING->value]) ? 1 : 0,
        ];

        $fieldsArray[$entityField->nome] = $fieldArray;

    }

    public function saveModelConf()
    {
        if (!$this->checkDaFare('modelconf')) {
            return;
        };


        $jsModelName = "Model" . $this->model->model_class;

        $modelsConfsFileName = $this->vueApplicationModelConfsPath . $jsModelName . '.js';

        $filename = base_path($modelsConfsFileName);

        $stub = $this->files->get($this->getStub('modelconf'));
        $variables = [];


        $searchValues = [];
        $listValues = [];
        $editValues = [];

        foreach ($this->model->fields as $entityField) {
            $this->buildModelConfValues($searchValues, $entityField, 'model_conf_search');
            $this->buildModelConfValues($lisVvalues, $entityField, 'model_conf_list');
            $this->buildModelConfValues($editValues, $entityField, 'model_conf_edit');

        }


        if ($this->model->has_foto) {
            $editValues['nome'][] = 'fotos';
            $editValues['type'][] = 'fotosEdit';
            $listValues['nome'][] = 'fotos';
            $listValues['type'][] = 'images';
            $listValues['order'][] = 'no';
        }
        if ($this->model->has_attachments) {
            $editValues['nome'][] = 'attachments';
            $editValues['type'][] = 'attachmentsEdit';
        }

        $variables['searchFields'] = $this->implodeArrayJsFields($searchValues);
        $variables['searchFieldsType'] = $this->implodeArrayJsFieldsType($searchValues);

        $variables['listFields'] = $this->implodeArrayJsFields($listValues);
        $variables['listFieldsType'] = $this->implodeArrayJsFieldsType($listValues);
        $variables['listOrderFields'] = $this->implodeArrayJsOrderFields($listValues);

        $variables['editFields'] = $this->implodeArrayJsFields($editValues);
        $variables['editFieldsType'] = $this->implodeArrayJsFieldsType($editValues);

        $stub = str_replace(
            '{{$snakeModelName}}', $this->snakeModel, $stub
        );

        foreach ($variables as $variableKey => $variableValue) {
            $stub = str_replace(
                '{{$' . $variableKey . '}}', $variableValue, $stub
            );
        }


//        print_r($stub);

        $this->files->put($filename, $stub);


        //AGGIORNO INDEX.JS
        $indexFileJsName = base_path($this->vueApplicationModelConfsPath . 'index.js');
        $indexJsFile = $this->files->get($indexFileJsName);

        $importString = "\nimport " . $jsModelName . " from './" . $jsModelName . ".js';";
        if (!Str::contains($indexJsFile, $importString)) {
            $indexJsFile = str_replace("//IMPORT START", "//IMPORT START" . $importString, $indexJsFile);
        }

        $installString = "\n\t\tcs.CrudVars.modelConfs." . $jsModelName . " = " . $jsModelName . ";";
        if (!Str::contains($indexJsFile, $installString)) {
            $indexJsFile = str_replace("//INSTALL START", "//INSTALL START" . $installString, $indexJsFile);
        }
        $this->files->put($indexFileJsName, $indexJsFile);

        //AGGIORNO MODELS.JSON
        $modelsJsonFilename = base_path($this->vueApplicationConfigPath . 'models.json');
        $modelsJsonFile = $this->getJsonFile($modelsJsonFilename);
        $modelsJsonFile[$jsModelName] = $jsModelName . '.js';
        $this->files->put($modelsJsonFilename,cupparis_pretty_json_encode($modelsJsonFile));




    }



    protected function implodeArrayJsFieldsType($fields)
    {

        $string = '';

        foreach ($fields as $field) {

            $type = Arr::get($field, 'type');
            $stub = $this->files->get($this->getStubInPath($type));

            $stub = str_replace(
                '{{$modelName}}', Str::snake($this->model->model_class), $stub
            );

            $string .= $this->getIndent(3) . "'" . Arr::get($field, 'nome') . "'";
            $string .= ' : { ' . "\n";
            $string .= $stub;
            $string .= $this->getIndent(3) . '}, ' . "\n";
        }

        $string = trim($string, " ,\n");

        return $string;
    }

    protected function implodeArrayJsOrderFields($fields)
    {

        $string = '';

        foreach ($fields as $field) {
            $string .= $this->getIndent(3) . "'" . Arr::get($field, 'nome') . "' : '" . Arr::get($field, 'nome') . "',\n";
        }

        $string = trim($string, " ,\n");

        return $string;
    }

    protected function implodeArrayJsFields($fields)
    {

        $string = '';

        foreach ($fields as $field) {
            $string .= $this->getIndent(3) . "'" . Arr::get($field, 'nome') . "',\n";
        }

        $string = trim($string, " ,\n");

        return $string;
    }

}
