<?php

namespace Gecche\Cupparis\App\Foorm\CupparisEntity\Actions;

use App\Models\CupparisEntityField;
use Carbon\Carbon;
use Gecche\Foorm\FoormAction;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class Rollback extends FoormAction
{
    use MigrateRollbackTrait;

    protected function init()
    {
        $this->initOps();

        parent::init(); // TODO: Change the autogenerated stub

    }


    public function performAction()
    {
        $this->rollbackLangs();
        $this->rollbackModelconf();
        $this->rollbackFoorm();
        $this->rollbackPolicy();
        $this->rollbackModel();
        $this->rollbackMigration();
        $this->manageConfigs($this->getConfigsData(), 'u');
        $this->actionResult = [

        ];

        return $this->actionResult;        // TODO: Implement performAction() method.
    }

    public function validateAction()
    {
        return true;
        // TODO: Implement validateAction() method.
    }

    public function rollbackLangs()
    {
        if (!$this->checkDaFare('lang')) {
            return;
        };
//
//        foreach ($this->langs['model'] as $modelLangFile) {
//            $langsModelData = [
//                [
//                    'configFile' => resource_path($modelLangFile),
//                    'keys' => [
//                        $this->snakeModel => [],
//                    ]
//                ],
//            ];
//            $this->manageConfigs($langsModelData,'u');
//        }

    }

    public function rollbackMigration()
    {

        if (!$this->checkDaFare('migration')) {
            return;
        };

        $migrationTable = $this->model->nome;

        $migrationFiles = $this->files->files(base_path($this->migrationPath));

        foreach ($migrationFiles as $migrationFile) {

            if (Str::endsWith($migrationFile, '_create_' . $migrationTable . '_table.php')) {
                $this->files->delete($migrationFile);
            }

        }

    }

    public function rollbackModelconf()
    {
        if (!$this->checkDaFare('modelconf')) {
            return;
        };

        $jsModelName = "Model" . $this->model->model_class;

        $modelsConfsFileName = $this->vueApplicationModelConfsPath . $jsModelName . '.js';

        $filename = base_path($modelsConfsFileName);

        if ($this->files->exists($filename)) {
            $this->files->delete($filename);
        }

        //AGGIORNO MODELS.JSON
        $modelsJsonFilename = base_path($this->vueApplicationConfigPath . 'models.json');
        $modelsJsonFile = $this->getJsonFile($modelsJsonFilename);
        Arr::pull($modelsJsonFile,$jsModelName);
        $this->files->put($modelsJsonFilename,cupparis_pretty_json_encode($modelsJsonFile));

        //AGGIORNO INDEX.JS
        $indexFileJsName = base_path($this->vueApplicationModelConfsPath . 'index.js');
        $indexJsFile = $this->files->get($indexFileJsName);

        $importString = "\nimport " . $jsModelName . " from './" . $jsModelName . ".js';";
        $installString = "\n\t\tcs.CrudVars.modelConfs." . $jsModelName . " = " . $jsModelName . ";";
        $indexJsFile = Str::replace([$importString, $installString], ["", ""], $indexJsFile);
        $this->files->put($indexFileJsName, $indexJsFile);
    }

    public function rollbackModel()
    {
        if (!$this->checkDaFare('modello')) {
            return;
        };

        $filename = base_path("app/Models/" . $this->model->model_class . '.php');

        if ($this->files->exists($filename)) {
            $this->files->delete($filename);
        }
//
//
//        /*
//         * SALVO I FIELDS NEL LANG
//         */
//
//        $configStubName = $this->getStub('config');
//        $configStub = $this->files->get($configStubName);
//
//        foreach ($this->langs['model'] as $modelLangFile) {
//            $this->saveResourceFile($modelLangFile, $configStub, 'model');
//        }
//
//        foreach ($this->langs['fields'] as $fieldsLangFile) {
//            $this->saveResourceFile($fieldsLangFile, $configStub, 'fields');
//        }
//
//        /*
//         * SALVO ANCHE PER LE ROUTES
//         * USO GLI STESSI METODI DEI LANGS
//         */
//
//        $cupparisAppJson = json_decode($this->files->get($this->cupparisAppJsonFile),true);
//
//        $jsonFoorms = Arr::get($cupparisAppJson,'foorm',[]);
//        $jsonEntities = Arr::get($jsonFoorms,'entities',[]);
//        $snakeModelName = Str::snake($this->modelName);
//        if (!in_array($snakeModelName,$jsonEntities)) {
//            $jsonEntities[] = $snakeModelName;
//        }
//        $jsonFoorms['entities'] = $jsonEntities;
//        $cupparisAppJson['foorm'] = $jsonFoorms;
//
//        $jsonPermissions = Arr::get($cupparisAppJson,'permissions',[]);
//        $jsonPermissionModels = Arr::get($jsonPermissions,'models',[]);
//        if (!in_array($snakeModelName,$jsonPermissionModels)) {
//            $jsonPermissionModels[] = $snakeModelName;
//        }
//        $jsonPermissions['models'] = $jsonPermissionModels;
//        $cupparisAppJson['permissions'] = $jsonPermissions;
//
//        $jsonPolicies = Arr::get($cupparisAppJson,'policies',[]);
//        $jsonPoliciesModels = Arr::get($jsonPolicies,'models',[]);
//        if (!in_array($snakeModelName,$jsonPoliciesModels)) {
//            $modelsNamespace ='\\' . ltrim(Arr::get($this->config,'models_namespace','App\\Models\\'),"\\");
//            $policiesNamespace ='\\' . ltrim(Arr::get($this->config,'policies_namespace','App\\Policies\\'),"\\");
//            $fullModelName = $modelsNamespace . $this->modelName;
//            $fullPolicyName = $policiesNamespace . $this->modelName . 'Policy';
//
//            $jsonPoliciesModels[$fullModelName] = $fullPolicyName;
//        }
//        $jsonPolicies['models'] = $jsonPoliciesModels;
//        $cupparisAppJson['policies'] = $jsonPolicies;
//
//        $this->files->put($this->cupparisAppJsonFile,json_encode($cupparisAppJson));
//

    }


    public function rollbackPolicy()
    {
        if (!$this->checkDaFare('policy')) {
            return;
        };


        $filename = base_path("app/Policies/" . $this->model->model_class . 'Policy.php');

        if ($this->files->exists($filename)) {
            $this->files->delete($filename);
        }

    }


    public function rollbackFoorm()
    {
        if (!$this->checkDaFare('foorm')) {
            return;
        };


        $filename = base_path("config/foorms/" . Str::snake($this->model->model_class) . '.php');

        if ($this->files->exists($filename)) {
            $this->files->delete($filename);
        }

    }


}
