<?php

namespace Gecche\Cupparis\App\Models;

use Gecche\Cupparis\App\Breeze\Breeze;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class CupparisEntity extends Breeze
{
    use Relations\CupparisEntityRelations;

    protected $table = 'cupparis_entities';

    protected $guarded = ['id'];

    public $timestamps = true;
    public $ownerships = true;

    public $appends = [
        'timestamps',
        'ownerships',
        'lang_singolare',
        'lang_plurale',
        'columns_list',
        'columns_order',
        'has_foto',
        'has_attachments',
    ];

    public $informazioniStructure = [
        'timestamps' => 'nullable',
        'ownerships' => 'nullable',
        'lang_singolare' => null,
        'lang_plurale' => null,
        'columns_list' => ['id'],
        'columns_order' => ['id_asc'],
        'has_foto' => 0,
        'has_attachments' => 0,
    ];

    protected $casts = [
        'informazioni' => 'array',
    ];


    public static $relationsData = [

        'fields' => array(self::HAS_MANY, 'related' => CupparisEntityField::class, 'table' => 'cupparis_entities_fields',
            'foreignKey' => 'entity_id'),


//        'belongsto' => array(self::BELONGS_TO, UnicoAttivita::class, 'foreignKey' => '<FOREIGNKEYNAME>'),
//        'belongstomany' => array(self::BELONGS_TO_MANY, UnicoAttivita::class, 'table' => '<TABLEPIVOTNAME>','pivotKeys' => [],'foreignKey' => '<FOREIGNKEYNAME>','otherKey' => '<OTHERKEYNAME>') ,
//        'hasmany' => array(self::HAS_MANY, UnicoAttivita::class, 'table' => '<TABLENAME>','foreignKey' => '<FOREIGNKEYNAME>'),
    ];

    public static $rules = [
//        'username' => 'required|between:4,255|unique:users,username',
    ];

    public $columnsForSelectList = ['nome'];
    //['id','descrizione'];

    public $defaultOrderColumns = ['updated_at' => 'DESC',];
    //['cognome' => 'ASC','nome' => 'ASC'];

    public $columnsSearchAutoComplete = ['nome'];
    //['cognome','denominazione','codicefiscale','partitaiva'];

    public $nItemsAutoComplete = 20;
    public $nItemsForSelectList = 100;
    public $itemNoneForSelectList = false;
    public $fieldsSeparator = ' - ';

    //
    public function save(array $options = [])
    {
        if (!$this->model_class) {
            $this->model_class = Str::studly($this->nome);
        }
        if (!$this->getKey() && is_null($this->informazioni)) {
            $this->informazioni = $this->informazioniStructure;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function getInformazioniField($field)
    {
        $informazioni = $this->informazioni;
        return Arr::get($informazioni, $field, Arr::get($this->informazioniStructure, $field));
    }

    public function setInformazioniField($field,$value)
    {
        $informazioni = $this->informazioni;
        $informazioni[$field] = $value;
        $this->informazioni = $informazioni;
    }

    /**
     * Handle dynamic method calls into the model.
     *
     * @param string $method
     * @param array $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        foreach (array_keys($this->informazioniStructure) as $fieldName) {
            $methodName = 'get' . Str::studly($fieldName) . 'Attribute';
            if ($methodName == $method) {
                return $this->getInformazioniField($fieldName);
            }
            $methodName = 'set' . Str::studly($fieldName) . 'Attribute';
            if ($methodName == $method) {
                return $this->setInformazioniField($fieldName,...$parameters);
            }
        }

        return parent::__call($method, $parameters);
        // TODO: Implement __call() method.
    }

    public function hasSetMutator($key)
    {
        return in_array($key,array_keys($this->informazioniStructure)) || method_exists($this, 'set'.Str::studly($key).'Attribute');
    }

    public function hasGetMutator($key)
    {
        return in_array($key,array_keys($this->informazioniStructure)) || method_exists($this, 'get'.Str::studly($key).'Attribute');
    }
}
